### ISSUE TITLE
Built in Dead Letter Queue Redrive Policies

### ISSUE THREAD

**Issue by henrymgarrett** [stacktape/stacktape#85]
As a user of Stacktape, I would like to be able to create an SQS queue, and dedicated dead letter queue with a specific redrive policy out of the box (without needing to use CloudFormation overrides).

We are currently doing it by creating two separate SQS queues, and inspecting the CloudFormation to figure out the overrides necessary.  Example below:

```
 mainQueue:
    type: sqs-queue
    properties:
    # send SQS messages that failed to process to our DLQ
    overrides:
      MainQueueQueue:
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - 'MainDLQQueue'
              - 'Arn'
          maxReceiveCount: 5

mainDLQQueue:
  type: sqs-queue
```

Would be nice to have something like:
  
```
mainQueue:
    type: sqs-queue
    properties:
       deadLetterQueue:
         redrivePolicy:
             maxReceiveCount: 5
```

**Comment by simi-obs** [comment]
the support for this was added in the recent release. Your use case can be configured like this
```yml
 mainQueue:
    type: sqs-queue
    properties:
      redrivePolicy:
        targetSqsQueueName: mainDLQQueue
        maxReceiveCount: 1

mainDLQQueue:
  type: sqs-queue

```
