### ISSUE TITLE
Dead Letter Queue Message Count Alarm Trigger Type

### ISSUE THREAD

**Issue by henrymgarrett** [stacktape/stacktape#88]
I would like to be able to alert if I'm starting to get messages into a dead letter queue

**Comment by simi-obs** [comment]
So in other words, you want to trigger alarm when queue is not empty. Correct?

I.e:
- Alarm goes into "alarm" state when the queue is not empty
- It would go back to "ok" state once queue is empty again

**Comment by henrymgarrett** [comment]
@simi-obs exactly!

**Comment by simi-obs** [comment]
Hey @henrymgarrett  so in version 2.6.4 we have released new alarm `sqs-queue-received-messages-count`, which could solve your problem

This trigger is fired based on messages being received by consumer from your SQS queue. 

**This means that the alarm only fires, if there is a consumer (i.e lambda) consuming from your DLQ queue.**

We are already working on some other solution, but it is not trivial as DLQ messages do not show up in the metrics same way as regular messages.

Let me know if this works for you

Here is an example of how you could use this alarm in your config:

```yml
resources:
  dlq:
    type: sqs-queue
    properties:
      alarms:
        - trigger:
            type: sqs-queue-received-messages-count
            properties:
              thresholdCount: 0
          notificationTargets:
            - type: slack
              properties:
                conversationId: CXXXXXXXXX
                accessToken: $Secret('slack-access-token')
```
