### ISSUE TITLE
Application Load Balancer Latency Alarm Trigger Type

### ISSUE THREAD

**Issue by henrymgarrett** [stacktape/stacktape#89]
I'd like to be able to alert on the latency of an Application Load Balancer

**Comment by simi-obs** [comment]
I am not sure if this would serve your case but we could implement an alarm using `TargetResponseTime` metric exposed by load balancer. 

This metric captures the time elapsed, in seconds, after the request leaves the load balancer until the target starts to send the response headers. 

So it only monitors the latency of your target (how long it took for lambda/container to respond). 

Would you be interested in something like this?

The thing is that we have to work with metrics that AWS exposes for load balancer and are available to us in Cloudwatch. Here is the list of these metrics: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html

and `TargetReponseTime` seems to be the closest to your needs

**Comment by henrymgarrett** [comment]
@simi-obs thanks for the explanation.  I think `TargetResponseTime` works well here.

Looking at that metrics page, I'd also be interested in `RequestCount` and `RejectedConnectionCount`

**Comment by simi-obs** [comment]
Hey @henrymgarrett ,
in the newest release (2.7.0) we have introduced a custom alarm trigger type for load balancer which can use any [metric exposed by AWS for load balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html). The example with target response time could look like this:
```yml
resources:
  myLoadBalancer:
    type: application-load-balancer
    properties:
      alarms:
        - trigger:
            type: application-load-balancer-custom
            properties:
              metric: TargetResponseTime
              threshold: 0.5
              statistic: avg
```
This should cover a lot of use cases, and we will introduce similar alarms for other resources as well.

We are also thinking about introducing ability to use more complex metrics math, but this needs some more work
